server:
  port: 80
spring:
  redis:
      host: localhost
      port: 6379
      password: 8txCAGCdFlMVWg02wszP
      timeout: 300
      database: 11
      pool:
        max-idle: 10
        max-wait: 5000
        max-active: 200
  datasource:
    url: jdbc:mysql://localhost:3306/yiren?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 5VJSkwZ0Bk#A
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 100
      # 配置获取连接等待超时的时间
      maxWait: 1000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 5000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      removeAbandoned: false
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 50
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=300;druid.stat.logSlowSql=true
      query-timeout-second: 2
      filters: stat

#mybatis&&通用Mapper
mybatis:
  type-aliases-package: cn.yirenzhuang.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: cn.yirenzhuang.common.mapper.BaseMapper
  not-empty: false
  identity: MYSQL
