server:
  port: 80
spring:
  redis:
      host: yirenzhuang.top
      port: 6379
      password: 8txCAGCdFlMVWg02wszP
      timeout: 300
      database: 0
      pool:
        max-idle: 10
        max-wait: 5000
        max-active: 200
  datasource:
    url: jdbc:mysql://yirenzhuang.top:3306/yirenzhuang?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 5VJSkwZ0Bk#A
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 50
      # 配置获取连接等待超时的时间
      maxWait: 6000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      removeAbandonedTimeout: 60
      removeAbandoned: true
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat=true

#mybatis&&通用Mapper
mybatis:
  type-aliases-package: cn.yirenzhuang.model
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: cn.yirenzhuang.common.mapper.BaseMapper
  not-empty: false
  identity: MYSQL


product:
  imguri: https://hmres.huimin100.cn/